### ISSUE TITLE
Unexpected behaviour of dir::get_size

### ISSUE THREAD

**Issue by gliderkite** [webdesus/fs_extra#25] opened 2019-10-04 10:32 UTC
In my application, I need to get the size of a directory, and in order to avoid having to re-invent the wheel I was planning to use the `dir::get_size` method provided by this library (thanks for your work!).

Unfortunately though, the results I am getting differ from the ones expected (I am targeting a Linux machine). This is because the implementation does not return the size of a directory, but the sum of all the sizes of its files, without taking into account the size of the directory structure itself.

You can quickly test this behaviour on a Linux machine by running the mention method on a given directory, and then running for the same directory the command `du --bytes -s {dir_path}`.

If this is the expected behaviour, I would simply suggest to explicitly state it in the documentation in a clear way.

If this is not the expected behaviour, it can be easily fixed by slightly changing the implementation:

```
pub fn get_size<P>(path: P) -> Result<u64>
where
    P: AsRef<Path>,
{
    let mut result = 0;

    if path.as_ref().is_dir() {
        for entry in read_dir(&path)? {
            let _path = entry?.path();
            if _path.is_file() {
                result += _path.metadata()?.len();
            } else {
                result += get_size(_path)?;
            }
        }
        // add the directory data structure size
        result += path.as_ref().metadata()?.len();
    } else {
        result = path.as_ref().metadata()?.len();
    }
    Ok(result)
}
```

I understand this will also require some work to update the tests to reflect the new implementation. Please let me know if support is needed for this (can't promise when I'll be able to have a deeper look into this in case it's required).

**Comment by webdesus** [comment] 2019-11-20 13:30
Sorry for the late response. I missed a notification about it... 
Answer your question:
Yes, it's expected behavior and unfortunately, i don't remember why... I was very busy this year... But soon i wan to return to the project and rewrite it. I wanna change API and realize new ideas(including yours) :smiley:

**Comment by AaronErhardt** [comment] 2020-12-02 22:01
I had the same problem. If this is the expected behaviour please note this in the documentation because for most people this is probably unexpected.

Also it'd be nice to know that `get_size` actually returns the amount of bytes not just a "size", so that should probably be added to the documentation.

If you want to change the behaviour but don't have time for this, I could try to create a PR for this problem. The problem should be fixed with a single additional line of code. But as already said tests will probably break. Also tests won't be reproducible any more (at least if the test directory contains further directories) because the folder size might vary in different file systems.

**Comment by webdesus** [comment] 2020-12-03 06:37
@AaronErhardt I would really appreciate your, if you send PR :blush: Or i can try on the weekend fix it by myself

**Comment by AaronErhardt** [comment] 2020-12-03 15:15
Here's my PR #34 :)

**Closed** 2022-09-20 09:32 UTC
